[supervisord]
nodaemon=true

[program:init]
directory=/var/www/html
command=sh -c 'rm -f storage/app/migration-lock && php artisan config:clear && php artisan cache:clear && php artisan route:clear && php artisan view:clear  && touch storage/app/migration-lock && php artisan config:cache && php artisan route:cache && tail -n 100 storage/logs/laravel.log'
autostart=true
autorestart=false
startsecs=0
priority=5
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
# [program:init]
# directory=/var/www/html
# command=sh -c 'php artisan config:clear && php artisan cache:clear && if [ ! -f storage/app/migration-lock ]; then echo "=== Running migrations and seeding for the first time ===" && php artisan migrate --force --database=pgsql_direct && php artisan db:seed --force --database=pgsql_direct && touch storage/app/migration-lock; else echo "=== Migrations and seeding already completed, skipping ==="; fi && php artisan config:cache && php artisan route:cache'
# autostart=true
# autorestart=false
# startsecs=0
# priority=5
# stdout_logfile=/dev/stdout
# stderr_logfile=/dev/stderr

[program:apache]
command=apache2-foreground
user=www-data
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:reverb]
directory=/var/www/html
command=php artisan reverb:start --host=0.0.0.0 --port=8080
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0