<?php

namespace Database\Seeders;

use App\Models\PharmacyDrugInventory;
use Illuminate\Database\Seeder;

class PharmacyDrugInventory1Seeder extends Seeder
{
    public function run(): void
    {
        $pharmacyId = 7;
        $inventories = [
            [
                'pharmacy_id'         => $pharmacyId,
                'drug_id'             => 1,
                'stock'               => 1240,
                'price'               => 45.00,
                'about_drug_en'       => 'Effective for mild to moderate pain and fever reduction.',
                'about_drug_am'       => 'ቀላል እና መካከለኛ ህመም እና ትኩሳትን ለመቀነስ ውጤታማ ነው።',
                'prescription_required' => false,
                'expire_date'         => '2027-10-15',
                'status'              => 'AVAILABLE',
            ],
            [
                'pharmacy_id'         => $pharmacyId,
                'drug_id'             => 2,
                'stock'               => 650,
                'price'               => 92.00,
                'about_drug_en'       => 'Broad spectrum antibiotic for bacterial infections.',
                'about_drug_am'       => 'ባክቴሪያ ኢንፌክሽንን ለማከም ሰፊ ስፔክትረም አንቲባዮቲክ።',
                'prescription_required' => true,
                'expire_date'         => '2026-12-20',
                'status'              => 'AVAILABLE',
            ],
            [
                'pharmacy_id'         => $pharmacyId,
                'drug_id'             => 3,
                'stock'               => 890,
                'price'               => 68.00,
                'about_drug_en'       => 'Used to manage type 2 diabetes.',
                'about_drug_am'       => 'አይነት 2 የስኳር በሽታን ለመቆጣጠር ያገለግላል።',
                'prescription_required' => true,
                'expire_date'         => '2028-05-10',
                'status'              => 'AVAILABLE',
            ],
            [
                'pharmacy_id'         => $pharmacyId,
                'drug_id'             => 4,
                'stock'               => 78,
                'price'               => 285.00,
                'about_drug_en'       => 'Quick relief inhaler for asthma and breathing problems.',
                'about_drug_am'       => 'አስም እና የመተንፈስ ችግርን በፍጥነት የሚያስታግስ ኢንሃለር።',
                'prescription_required' => false,
                'expire_date'         => '2027-07-05',
                'status'              => 'AVAILABLE',
            ],
            [
                'pharmacy_id'         => $pharmacyId,
                'drug_id'             => 5,
                'stock'               => 430,
                'price'               => 55.00,
                'about_drug_en'       => 'Reduces stomach acid and treats ulcers and heartburn.',
                'about_drug_am'       => 'የሆድ አሲድን የሚቀንስ እና ቁስለትን የሚያክም።',
                'prescription_required' => false,
                'expire_date'         => '2027-11-30',
                'status'              => 'AVAILABLE',
            ],
            [
                'pharmacy_id'         => $pharmacyId,
                'drug_id'             => 6,
                'stock'               => 520,
                'price'               => 38.00,
                'about_drug_en'       => 'Antihistamine for allergy relief.',
                'about_drug_am'       => 'አለርጂን ለማስታገስ የሚያገለግል አንቲሂስታሚን።',
                'prescription_required' => false,
                'expire_date'         => '2027-09-18',
                'status'              => 'AVAILABLE',
            ],
            [
                'pharmacy_id'         => $pharmacyId,
                'drug_id'             => 7,
                'stock'               => 310,
                'price'               => 75.00,
                'about_drug_en'       => 'Anti-inflammatory for pain and swelling.',
                'about_drug_am'       => 'ህመም እና እብጠትን ለመቀነስ አንቲ-ኢንፍላማቶሪ።',
                'prescription_required' => false,
                'expire_date'         => '2026-11-25',
                'status'              => 'AVAILABLE',
            ],
            [
                'pharmacy_id'         => $pharmacyId,
                'drug_id'             => 8,
                'stock'               => 680,
                'price'               => 110.00,
                'about_drug_en'       => 'Calcium channel blocker for hypertension.',
                'about_drug_am'       => 'የደም ግፊትን ለመቆጣጠር የሚያገለግል።',
                'prescription_required' => true,
                'expire_date'         => '2028-02-28',
                'status'              => 'AVAILABLE',
            ],
            [
                'pharmacy_id'         => $pharmacyId,
                'drug_id'             => 9,
                'stock'               => 950,
                'price'               => 25.00,
                'about_drug_en'       => 'Vitamin C supplement for immunity.',
                'about_drug_am'       => 'በሽታ የመከላከል አቅምን ለማጎልበት ቫይታሚን ሲ።',
                'prescription_required' => false,
                'expire_date'         => '2027-12-10',
                'status'              => 'AVAILABLE',
            ],
            [
                'pharmacy_id'         => $pharmacyId,
                'drug_id'             => 10,
                'stock'               => 180,
                'price'               => 145.00,
                'about_drug_en'       => 'Antibiotic used for respiratory and skin infections.',
                'about_drug_am'       => 'የመተንፈሻ እና የቆዳ ኢንፌክሽን ለማከም አንቲባዮቲክ።',
                'prescription_required' => true,
                'expire_date'         => '2026-08-05',
                'status'              => 'AVAILABLE',
            ],
            [
                'pharmacy_id'         => $pharmacyId,
                'drug_id'             => 11,
                'stock'               => 410,
                'price'               => 52.00,
                'about_drug_en'       => 'Pain reliever and anti-inflammatory.',
                'about_drug_am'       => 'ህመም ማስታገሻ እና አንቲ-ኢንፍላማቶሪ።',
                'prescription_required' => false,
                'expire_date'         => '2027-06-22',
                'status'              => 'AVAILABLE',
            ],
            [
                'pharmacy_id'         => $pharmacyId,
                'drug_id'             => 12,
                'stock'               => 275,
                'price'               => 98.00,
                'about_drug_en'       => 'Antibiotic for urinary tract and gastrointestinal infections.',
                'about_drug_am'       => 'የሽንት ቱቦ እና የሆድ ኢንፌክሽን ለማከም አንቲባዮቲክ።',
                'prescription_required' => true,
                'expire_date'         => '2026-10-12',
                'status'              => 'AVAILABLE',
            ],
            [
                'pharmacy_id'         => $pharmacyId,
                'drug_id'             => 13,
                'stock'               => 560,
                'price'               => 85.00,
                'about_drug_en'       => 'ACE inhibitor for high blood pressure.',
                'about_drug_am'       => 'ከፍተኛ የደም ግፊትን ለመቆጣጠር ACE ኢንሂቢተር።',
                'prescription_required' => true,
                'expire_date'         => '2028-01-15',
                'status'              => 'AVAILABLE',
            ],
            [
                'pharmacy_id'         => $pharmacyId,
                'drug_id'             => 14,
                'stock'               => 340,
                'price'               => 48.00,
                'about_drug_en'       => 'Antifungal cream for skin infections.',
                'about_drug_am'       => 'የቆዳ ፈንገስ ኢንፌክሽንን ለማከም አንቲፈንጋል።',
                'prescription_required' => false,
                'expire_date'         => '2027-04-30',
                'status'              => 'AVAILABLE',
            ],
            [
                'pharmacy_id'         => $pharmacyId,
                'drug_id'             => 15,
                'stock'               => 1200,
                'price'               => 22.00,
                'about_drug_en'       => 'Essential for pregnant women and blood formation.',
                'about_drug_am'       => 'ለነፍሰ ጡር ሴቶች እና ደም ለመፍጠር አስፈላጊ ነው።',
                'prescription_required' => false,
                'expire_date'         => '2028-03-05',
                'status'              => 'AVAILABLE',
            ],
        ];

        foreach ($inventories as $inventory) {
            PharmacyDrugInventory::create($inventory);
        }
    }
}
